### PR TITLE
Refactor/camelCase

### LINKED ISSUE #42: Refactoring everything to camelCase
Refactoring the filenames, class names and everything else that isn't bootstrap to camelCase for readability.

### PR DESCRIPTION
**Pull request by Simber1**
Still WIP
Edit: Ready to be reviewed.
This closes #42

### CODE REVIEW

**Comment by Simber1** [comment]
I'd say this is ready to go to master, with it being such a big change involving all pages I would like this to be reviewed by a few people before I merge it.

**Comment by KommToby** [comment]
_i got u bro_

**Comment by Simber1** [comment]
> _i got u bro_

reeee

**Review by KommToby — APPROVED** [review]
Yep

**Pull request merged**
